// export const SOCKET_SERVER_URL = 'http://localhost:5624'
// // export const API_KEY_GOOGLE = 'AIzaSyAknWQFyVH1RpR2OAL0vRTHTapaIpfKSqo'
// export const API_KEY_GOOGLE = 'AIzaSyANFq2lA9u6899KtCz_WZlpWAj3fdxPyRE'
// export const URL_SERVER_SOCKET_PEDIDO = 'http://192.168.1.39:5819'
// export const URL_SERVER_PEDIDO = 'http://192.168.1.39:5819/v3/'

// export const PUBLIC_AWS_SECRET_ACCESS_KEY = 'qp4P9XTZK2+ORtuVNftzpMCQtFdSclJUCmWODdHI'
// export const PUBLIC_AWS_REGION = 'EE. UU. Este (Ohio) us-east-2'
// export const PUBLIC_BUCKET_NAME = 'arn:aws:s3:::papaya-comercio-files/files-bot/'
// export const PUBLIC_URL_VIEW_BUCKET = 'https://papaya-comercio-files/files-bot/'